project:
  type: website

website:
  title: "Ziang Liu"
  favicon: images/favicon.ico
  site-url: https://zi-ang-liu.github.io
  description: "Ziang Liu's Personal Website"
  open-graph: true
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "Blog"
        href: blog.qmd
    right:
      - text: "Open Source"
        href: open-source.qmd
      - icon: github
        href: https://github.com/zi-ang-liu
  page-footer: 
    center: "Copyright 2025, Ziang Liu"
    right: |
      [法政大学](https://www.hosei.ac.jp/)
      [経営システム工学科](https://ise-hp.ws.hosei.ac.jp/)
      [知能システム研究室](https://isl-hosei.github.io/)
    border: true
format:
  html:
    theme:
      light: Minty
      dark: darkly
    css: styles.css


# default
# cerulean
# cosmo
# cyborg
# darkly
# flatly
# journal
# litera
# lumen
# lux
# materia
# minty
# morph
# pulse
# quartz
# sandstone
# simplex
# sketchy
# slate
# solar
# spacelab
# superhero
# united
# vapor
# yeti
# zephyr