project:
  type: website

website:
  title: "Ziang Liu"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
    right:
      - icon: github
        href: https://github.com/zi-ang-liu
  page-footer: 
    left:
      "Copyright 2025, Ziang Liu" 
    right: 
      - icon: github
        href: https://github.com/zi-ang-liu
    border: true
    background: dark
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
favicon: https://github.com/zi-ang-liu.png