project:
  type: website

website:
  title: "Ziang Liu"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Teaching"
        href: teaching.qmd
    right:
      - icon: github
        href: https://github.com/zi-ang-liu
  page-footer: 
    # left: |
    #   [ResearchGate](https://www.researchgate.net/profile/Ziang-Liu-4) <br>
    #   [ORCID](https://orcid.org/0000-0002-1364-3502) <br>
    #   [ResearchMap](https://researchmap.jp/liu.ziang) <br>
    #   [Kaken](https://nrid.nii.ac.jp/ja/nrid/1000030908166/)
    center: "Copyright 2025, Ziang Liu"
    right: |
      [法政大学](https://www.hosei.ac.jp/)
      [経営システム工学科](https://ise-hp.ws.hosei.ac.jp/)
      [知能システム研究室](https://isl-hosei.github.io/)
    border: true
format:
  html:
    theme:
      - Darkly
    css: styles.css
favicon: https://github.com/zi-ang-liu.png