project:
  type: website

website:
  title: "Ziang Liu"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Blog"
        href: blog.qmd
    right:
      - icon: github
        href: https://github.com/zi-ang-liu
  page-footer: 
    center: "Copyright 2025, Ziang Liu"
    right: |
      [法政大学](https://www.hosei.ac.jp/)
      [経営システム工学科](https://ise-hp.ws.hosei.ac.jp/)
      [知能システム研究室](https://isl-hosei.github.io/)
    border: true
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
favicon: https://github.com/zi-ang-liu.png