site_name: Ziang Liu
site_url: https://zi-ang-liu.github.io/
site_author: Ziang Liu
copyright: Copyright &copy; 2021 Ziang Liu
site_description: Ziang Liu's personal website

theme:  
  name: material
  features:  
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono

  icon:
    # logo: material/infinity
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  features:
    
  favicon: images/favicon_io/favicon.ico
  
  palette: 
    primary: indigo

nav:
  - Home: index.md
  - ホーム: ja/index.md
  - 担当科目: ja/course.md
  - 資料: ja/material.md
  # - Blog:
  #   - blog/index.md

extra:
  social:
    - icon: fontawesome/brands/google 
      link: https://scholar.google.com/citations?user=dRuC1OoAAAAJ&hl
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Ziang-Liu-4
    - icon: simple/orcid
      link: https://orcid.org/0000-0002-1364-3502
    - icon: fontawesome/brands/github
      link: https://github.com/zi-ang-liu/

  generator: false

  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Japanese
  #     link: /ja/
  #     lang: ja

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/extra.css

plugins:
  # - blog
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  