site_name: Liu Ziang
  
theme:
  
  name: material

  icon:
    logo: material/school
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  favicon: images/favicon/favicon-16x16.png

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - content.code.copy
    # - toc.integrate
  
  palette: 
  
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Page tree
nav:
  - Home: index.md
  - Publications: publications.md
  - Teaching: 
    - Courses: teaching.md
    # - C Programming: 
    #   - 講義資料: courses/c_programming/material.md
    #   - 演習問題（前半）: courses/c_programming/prob_1.md
    #   - 演習問題（後半）: courses/c_programming/prob_2.md
    # - AI with Python:
    #   - 講義資料: courses/ai_python/materal.md
    # - 研究指導: 
    #   - 参考文献: blog/参考文献.md
  - Links: links.md

extra:
  social:
    - icon: fontawesome/brands/google 
      link: https://scholar.google.com/citations?hl=en&user=_G5ufOEAAAAJ
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Ziang-Liu-4
    # - icon: fontawesome/brands/Orcid
    #   link: https://orcid.org/0000-0002-1364-3502
    - icon: fontawesome/brands/github
      link: https://github.com/zi-ang-liu/

  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: 日本語
  #     link: /jp/
  #     lang: jp
#     - name: 中文
#       link: /zh/
#       lang: zh

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/extra.css


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
