site_name: Liu Ziang
  
theme:
  
  name: material

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    # logo: material/infinity
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  favicon: images/favicon_io/favicon.ico

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - content.code.copy
    # - toc.integrate
  
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Page tree
nav:
  - Home: index.md
  - Publications: publications.md

extra:
  social:
    - icon: fontawesome/brands/google 
      link: https://scholar.google.com/citations?hl=en&user=_G5ufOEAAAAJ
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Ziang-Liu-4
    - icon: simple/orcid
      link: https://orcid.org/0000-0002-1364-3502
    - icon: fontawesome/brands/github
      link: https://github.com/zi-ang-liu/

  generator: false
  
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: 日本語
  #     link: /jp/
  #     lang: jp
#     - name: 中文
#       link: /zh/
#       lang: zh

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/extra.css

copyright: Copyright &copy; 2021 Ziang Liu

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  