---
title: "Kinoden 書籍リスト"
author: "劉子昂"
date: today
categories: [news]
---

法政大学図書館のKinodenで豊富な書籍を閲覧できます．

Kinodenは、下記のリンクからアクセスできます．

[KinoDen](https://kinoden.kinokuniya.co.jp/hosei_u/)

## Python入門

- [Python言語によるプログラミングイントロダクション　第2版 (2017)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00012323)
- [ChatGPTと学ぶPython入門](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00101216)
- [よくわかる Python入門](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00070311)
- [スッキリわかるPython入門](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00020952)
- [ゼロからやさしくはじめるPython入門](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00074160)
- [マンガでざっくり学ぶPython（パイソン）](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00036441)

## 経営工学

### Pythonで経営工学を学ぶ

- [Python コンピュータシミュレーション入門 (2021)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00045049)
  - Keywords: 感染症モデル，線型計画法，在庫管理，待ち行列，グラフ理論，遺伝的アルゴリズム，ゲーム理論，強化学習
  - 経営工学に関するテーマが多く取り上げられている．

### Excelで経営工学を学ぶ

- [入門　経営科学　改訂版](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00009061)
- [例題で学ぶ　OR入門](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00026069)
- [Excelで学ぶオペレーションズリサーチ](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00012267)
  

## 最適化

### Pythonで数理最適化を学ぶ

- [Pythonではじめる数理最適化　第2版 (2024)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00096408)
  - Keywords: 数理最適化，モデリング，ケーススタディ（学校のクラス編成，配送計画，商品推薦）
- [Pythonによる実務で役立つ最適化問題100+ 1 (2022)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00075057)
  - 栄養問題、最短路問題など
  - 内容が公開されている．[Link](https://scmopt.github.io/opt100/)
- [Pythonによる数理最適化入門 (2018)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00019214)
- [あたらしい数理最適化 (2012)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00012255)
  - Keywords: 施設配置問題、箱詰め問題と切断問題、スケジューリング問題など

### ソースコードなし

- [最適化の基礎](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00026109)

## 機械学習

### Pythonで機械学習を学ぶ

- [Python機械学習プログラミング (2022)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00074705)
  - Keywords: データ前処理，教師あり学習，教師なし学習，強化学習，Sklearn，PyTorch
  - 機械学習アルゴリズムの理論と実装を学べる．数学，プログラミングの両方に自信がある人向け．
- [スッキリわかるPythonによる機械学習入門](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00033550)
  - Keywords: 教師あり学習，教師なし学習
  - 機械学習ライブラリの使い方を学べる．数式が苦手な人向け．
- [いちばんやさしいPython機械学習の教本](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00020950)

## データサイエンス

### Pythonでデータサイエンスを学ぶ

- [データサイエンス教本(2018)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00024399)
  - Keywords: 回帰分析，パターン認識，深層学習，時系列分析，画像処理
- [Python時系列分析クックブック](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00086661)
- [Pythonによる実務で役立つデータサイエンス練習問題 200+ 1 (2023)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00080843)
  - Keywords: 練習問題

### ソースコードなし

- [データサイエンス入門　第3版](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00111095)
- [データ分析とデータサイエンス](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00012305)

## 統計学

### Pythonで統計学を学ぶ

- [Pythonで学ぶあたらしい統計学の教科書　第2版](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00076226)
- [Pythonで学ぶ統計的機械学習](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00024397)

### Rで統計学を学ぶ

- [理工系のための統計入門 (2016)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00015811)
- [Ｒによる統計解析](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00009885)

### ソースコードなし

- [数理統計学の基礎 (2014)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00041474)
- [教養のための統計入門 (2016)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00015809)
- [新統計入門 (1996)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00006257)
- [確率統計 (1996)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00006534)
- [確率・統計 (2019)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00043788)
- [経営科学のための確率統計入門 (2022)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00082989)

## システム工学

- [システム工学 (1996)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00008701)

## XAI

- [実践XAI［説明可能なAI］ (2023)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00081538)

## 強化学習

- [TensorFlowによる深層強化学習入門 (2021)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00041820)
- [強化学習アルゴリズム入門 (2019)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00024416)
- [現場で使える！Python深層強化学習入門 (2019)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00034524)


## 人工知能

- [人工知能入門](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00041467)
  - Keywords: 探索，推論，学習，進化的計算，ニューラルネットワーク，強化学習
- [人工知能原理](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00026096)
  - Keywords: 探索，機械学習，進化的計算，強化学習
- [基礎から学ぶ人工知能の教科書](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00031488)
  - Keywords: 学習，推論，深層学習，進化的計算，強化学習
- [人工知能の創発](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00011749)
- [タイトルメタヒューリスティクスとナチュラルコンピューティング](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00008641)
  - Keywords: 遺伝的アルゴリズム，粒子群最適化法，タブーサーチ，山登り法
- [AI時代の離散数学 (2020)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00032062)
  - Keywords: 論理関数，深層学習，グラフ理論，ネットワーク最適化

## アルゴリズム

- アルゴリズムイントロダクション
  - **世界的名著**
  - [アルゴリズムイントロダクション　第4版　1 (2024)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00087879)
  - [アルゴリズムイントロダクション　第4版　2 (2024)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00080844)
- [データ構造とアルゴリズム (2017)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00026089)

## モデリング

- [グラフ理論入門(原書第4版) (2001)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00016566)
- [マルコフ決定過程 (2019)](https://kinoden.kinokuniya.co.jp/hosei_u/bookdetail/p/KP00034289)


